name: deploy

on:
  push:
    branches:
      - master
    tags:
      - v*

permissions:
  contents: read
  id-token: write

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # @see: https://github.com/google-github-actions/auth#configuring-gcloud
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
          # @see: https://github.com/google-github-actions/auth#setting-up-workload-identity-federation
          # workload_identity_provider: 'projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
          # service_account: 'my-service-account@my-project.iam.gserviceaccount.com'

      # @see: https://github.com/docker/login-action#google-container-registry-gcr
      - name: Login to GCR
        uses: docker/login-action@v2
        with:
          registry: gcr.io
          # username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}
          username: _json_key
          # password: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            gcr.io/til-playground-338907/release-test
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
