name: release

on:
  workflow_run:
    workflows: [test]
    branches: [master]
    types: [completed]

jobs:
  version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v2

      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          package-name: release-please-action

  docker:
    runs-on: ubuntu-latest
    needs: version
#    if: ${{ needs.version.outputs.release_created }}
    permissions:
      contents: read
      id-token: write
    steps:
      - name: test
        run: echo ${{ needs.version.outputs }}
