name: release

on:
  workflow_run:
    workflows: [test]
    branches: [master]
    types: [completed]

jobs:
  version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v2

      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
          package-name: release-please-action

    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
      major: ${{ steps.release.outputs.major }}
      minor: ${{ steps.release.outputs.minor }}
      patch: ${{ steps.release.outputs.patch }}

  docker:
    runs-on: ubuntu-latest
    needs: version
    if: ${{ needs.version.outputs.release_created }}
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            gcr.io/til-playground-338907/release-test
          tags: |
            type=semver,pattern={{version}},value=${{ needs.version.outputs.tag_name }}
            type=semver,pattern={{major}}.{{minor}},value=${{ needs.version.outputs.tag_name }}
            type=semver,pattern={{major}},value=${{ needs.version.outputs.tag_name }}
            type=sha
